#! Name
name: sip3-captain

#! Vert.x
#vertx:
#  instances: 1

#! DPDK
#dpdk:
#  port: 0
#  rx-queue-size: 1
#  bulk-size: 256

#! Pcap (libpcap, WinPcap, Npcap)
#pcap:
#  dir: /tmp/sip3-captain
#  dev: eth0
#  bpf-filter: udp
#  timeout-millis: 10

#! TCP
#tcp:
#  expiration-delay: 100
#  aggregation-timeout: 100
#  idle-connection-timeout: 300000

#! Sender
sender:
  uri: udp://127.0.0.1:15060
#  reconnection-timeout: 1000
#  ssl:
#    key-store: ...
#    key-store-password: ...


#! Metrics
#metrics:
#  logging:
#    step: 1000
#  influxdb:
#    uri: http://127.0.0.1:8086
#    db: sip3
#    step: 1000
#    retention-duration: 7d