#! Name
name: sip3-captain

#! Vert.x
#vertx:
#  instances: 1

#! DPDK
#dpdk:
#  port: 0
#  rx-queue-size: 1
#  bulk-size: 256

#! Pcap (libpcap, WinPcap, Npcap)
#pcap:
#  dir: /tmp/sip3-captain
#  dev: eth0
#  bpf-filter: udp
#  timeout-millis: 10

#! TCP
#tcp:
#  expiration-delay: 100
#  aggregation-timeout: 100
#  idle-connection-timeout: 300000

#! Sender
sender:
  uri: udp://127.0.0.1:15060
#  reconnection-timeout: 1000
#  ssl:
#    key-store: ...
#    key-store-password: ...

#! Hosts
#hosts:
#  - name: sbc.sip3.io
#    sip:
#      - 10.10.10.10
#      - 10.10.10.20:5060
#    media:
#      - 10.10.20.10
#      - 10.10.30.0/24
#  - name: lb.sip3.io
#    sip:
#      - 10.20.10.10
#      - 10.20.10.20:5060

#! RTCP
#rtcp:
#  bulk-size: 128
#  expiration-delay: 4000
#  aggregation-timeout: 30000

#! ManagementSocket
#management:
#  schema: udp
#  local-host: 127.0.0.1:15090
#  remote-host: 127.0.0.1:15091
#  register-delay: 60000

#! Metrics
#metrics:
#  logging:
#    step: 1000
#  influxdb:
#    uri: http://127.0.0.1:8086
#    db: sip3
#    step: 1000
#    retention-duration: 7d
#  stasd:
#    host: 127.0.0.1
#    port: 8125
#    step: 1000
#    flavour: datadog
#  elastic:
#    host: http://127.0.0.1:9200
#    index: sip3
#    step: 1000